#其他配置的路径都是相对于当前文件路径
_BASE_: [
  '../datasets/coco_detection.yml', #训练所需数据集
  '_base_/detr_r50.yml', #网络结构
  '_base_/optimizer_1x.yml', #优化器配置

  '_base_/detr_reader.yml', #数据读取以及数据加强
  '../runtime.yml',  #运行时候的配置
]
weights: output/detr_r50_1x_coco/model_final
find_unused_parameters: True

# EvalReader
# #其他配置的路径都是相对于当前文件路径
# _BASE_: [
#   '../datasets/coco_detection.yml', #训练所需数据集
#   '_base_/rtdetr_r50vd.yml', #网络结构
#   '_base_/optimizer_6x.yml', #优化器配置

#   '_base_/rtdetr_reader.yml', #数据读取以及数据加强
#   '../runtime.yml', #运行时候的配置 共享运行参数配置目录
# ]

# weights: output/rtdetr_r50vd_6x_coco/model_final 
# find_unused_parameters: True
# log_iter: 200
